[program:celery]
command=/mnt/FuraOJ/furaojsite/bin/celery -A dmoj_celery worker
directory=/mnt/FuraOJ/site
user=furaoj
group=furaoj
autostart=true
autorestart=true
stdout_logfile=/mnt/FuraOJ/logs/celery.stdout.log
stderr_logfile=/mnt/FuraOJ/logs/celery.stderr.log