[program:site]
command=/mnt/FuraOJ/furaojsite/bin/uwsgi --ini uwsgi.ini
directory=/mnt/FuraOJ/site
stopsignal=QUIT
user=furaoj
group=furaoj
autostart=true
autorestart=true
stdout_logfile=/mnt/FuraOJ/logs/site.stdout.log
stderr_logfile=/mnt/FuraOJ/logs/site.stderr.log