[program:wsevent]
command=/usr/bin/node /mnt/FuraOJ/site/websocket/daemon.js
environment=NODE_PATH="/mnt/FuraOJ/site/node_modules"
user=furaoj
group=furaoj
autostart=true
autorestart=true
stdout_logfile=/mnt/FuraOJ/logs/wsevent.stdout.log
stderr_logfile=/mnt/FuraOJ/logs/wsevent.stderr.log